version: '2'

services:
  web:
    container_name: application
    ports:
      - "4200:4200"
    volumes:
      - "./seedy:/var/app"
    build:
      context: .
      dockerfile: node.dockerfile
    networks:
      - default_network

networks:
  default_network:
    driver: bridge